-- Create "like_protocols" table
CREATE TABLE "like_protocols" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "address" character varying NOT NULL, "latest_event_block_number" numeric NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "uint64_latest_event_block_number_check" CHECK (latest_event_block_number >= (0)::numeric));
-- Create index "like_protocols_address_key" to table: "like_protocols"
CREATE UNIQUE INDEX "like_protocols_address_key" ON "like_protocols" ("address");
