-- Create "accounts" table
CREATE TABLE "accounts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "cosmos_address" character varying NULL, "evm_address" character varying NOT NULL, "likeid" character varying NULL, PRIMARY KEY ("id"));
-- Create index "accounts_evm_address_key" to table: "accounts"
CREATE UNIQUE INDEX "accounts_evm_address_key" ON "accounts" ("evm_address");
-- Create index "accounts_likeid_key" to table: "accounts"
CREATE UNIQUE INDEX "accounts_likeid_key" ON "accounts" ("likeid");
-- Create "evm_events" table
CREATE TABLE "evm_events" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "transaction_hash" character varying NOT NULL, "block_hash" character varying NOT NULL, "block_number" bigint NOT NULL, "log_index" bigint NOT NULL, "address" character varying NOT NULL, "topic0" character varying NOT NULL, "topic1" character varying NOT NULL, "topic2" character varying NOT NULL, "topic3" character varying NOT NULL, "data" character varying NOT NULL, "timestamp" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "evm_events_transaction_hash_key" to table: "evm_events"
CREATE UNIQUE INDEX "evm_events_transaction_hash_key" ON "evm_events" ("transaction_hash");
-- Create "nft_classes" table
CREATE TABLE "nft_classes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "address" character varying NOT NULL, "name" character varying NOT NULL, "symbol" character varying NOT NULL, "owner_address" character varying NULL, "minter_addresses" jsonb NULL, "total_supply" bigint NOT NULL, "metadata" jsonb NULL, "banner_image" character varying NOT NULL, "featured_image" character varying NOT NULL, "deployer_address" character varying NOT NULL, "deployed_block_number" character varying NOT NULL, "minted_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "account_nft_classes" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "nft_classes_accounts_nft_classes" FOREIGN KEY ("account_nft_classes") REFERENCES "accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "nft_classes_address_key" to table: "nft_classes"
CREATE UNIQUE INDEX "nft_classes_address_key" ON "nft_classes" ("address");
-- Create "nf_ts" table
CREATE TABLE "nf_ts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "token_id" bigint NOT NULL, "token_url" character varying NULL, "raw" jsonb NULL, "name" character varying NOT NULL, "description" character varying NULL, "image" jsonb NULL, "attributes" jsonb NULL, "owner_address" character varying NOT NULL, "minted_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "account_nfts" bigint NULL, "nft_class_nfts" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "nf_ts_accounts_nfts" FOREIGN KEY ("account_nfts") REFERENCES "accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "nf_ts_nft_classes_nfts" FOREIGN KEY ("nft_class_nfts") REFERENCES "nft_classes" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "nf_ts_token_id_key" to table: "nf_ts"
CREATE UNIQUE INDEX "nf_ts_token_id_key" ON "nf_ts" ("token_id");
