FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    make \
    build-essential \
    gcc \
    pkg-config \
    python3-dev \
    libcairo2 \
    libcairo2-dev \
    libffi-dev \
    fonts-dejavu-core \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN ["make", "setup-dev"]

EXPOSE 8000

CMD ["make", "dev"]
