// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AccountByBookNFT implements accountByBookNFT operation.
//
// Query account by BookNFT.
//
// GET /booknft/{id}/account
func (UnimplementedHandler) AccountByBookNFT(ctx context.Context, params AccountByBookNFTParams) (r *AccountByBookNFTOK, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNFT implements bookNFT operation.
//
// Query BookNFT.
//
// GET /booknft/{id}
func (UnimplementedHandler) BookNFT(ctx context.Context, params BookNFTParams) (r *BookNFT, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNFTs implements bookNFTs operation.
//
// Query all BookNFTs.
//
// GET /booknfts
func (UnimplementedHandler) BookNFTs(ctx context.Context, params BookNFTsParams) (r *BookNFTsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNFTsByAccount implements bookNFTsByAccount operation.
//
// Query booknfts by account.
//
// GET /account/{evm_address}/booknfts
func (UnimplementedHandler) BookNFTsByAccount(ctx context.Context, params BookNFTsByAccountParams) (r *BookNFTsByAccountOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Events implements events operation.
//
// Query events.
//
// GET /events
func (UnimplementedHandler) Events(ctx context.Context, params EventsParams) (r *EventsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// EventsByAddress implements eventsByAddress operation.
//
// Query events.
//
// GET /events/{address}
func (UnimplementedHandler) EventsByAddress(ctx context.Context, params EventsByAddressParams) (r *EventsByAddressOK, _ error) {
	return r, ht.ErrNotImplemented
}

// EventsByAddressAndSignature implements eventsByAddressAndSignature operation.
//
// Query events.
//
// GET /events/{address}/{signature}
func (UnimplementedHandler) EventsByAddressAndSignature(ctx context.Context, params EventsByAddressAndSignatureParams) (r *EventsByAddressAndSignatureOK, _ error) {
	return r, ht.ErrNotImplemented
}

// IndexActionBookNftBooknftIDPost implements POST /index-action/book-nft/{booknft_id} operation.
//
// POST /index-action/book-nft/{booknft_id}
func (UnimplementedHandler) IndexActionBookNftBooknftIDPost(ctx context.Context, params IndexActionBookNftBooknftIDPostParams) (r *IndexActionBookNftBooknftIDPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// IndexActionLikeProtocolPost implements POST /index-action/like-protocol operation.
//
// POST /index-action/like-protocol
func (UnimplementedHandler) IndexActionLikeProtocolPost(ctx context.Context, params IndexActionLikeProtocolPostParams) (r *IndexActionLikeProtocolPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Token implements token operation.
//
// Query token.
//
// GET /token/{booknft_id}/{token_id}
func (UnimplementedHandler) Token(ctx context.Context, params TokenParams) (r *NFT, _ error) {
	return r, ht.ErrNotImplemented
}

// TokensByAccount implements tokensByAccount operation.
//
// Query tokens by account.
//
// GET /account/{evm_address}/tokens
func (UnimplementedHandler) TokensByAccount(ctx context.Context, params TokensByAccountParams) (r *TokensByAccountOK, _ error) {
	return r, ht.ErrNotImplemented
}

// TokensByBookNFT implements tokensByBookNFT operation.
//
// Query tokens by BookNFT.
//
// GET /booknft/{id}/tokens
func (UnimplementedHandler) TokensByBookNFT(ctx context.Context, params TokensByBookNFTParams) (r *TokensByBookNFTOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
