// Code generated by ent, DO NOT EDIT.

package ent_timescale

import (
	"context"
	"likecollective-indexer/ent_timescale/booknftdeltatimebucket30d"
	"likecollective-indexer/ent_timescale/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BookNFTDeltaTimeBucket30dDelete is the builder for deleting a BookNFTDeltaTimeBucket30d entity.
type BookNFTDeltaTimeBucket30dDelete struct {
	config
	hooks    []Hook
	mutation *BookNFTDeltaTimeBucket30dMutation
}

// Where appends a list predicates to the BookNFTDeltaTimeBucket30dDelete builder.
func (_d *BookNFTDeltaTimeBucket30dDelete) Where(ps ...predicate.BookNFTDeltaTimeBucket30d) *BookNFTDeltaTimeBucket30dDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BookNFTDeltaTimeBucket30dDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookNFTDeltaTimeBucket30dDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BookNFTDeltaTimeBucket30dDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(booknftdeltatimebucket30d.Table, sqlgraph.NewFieldSpec(booknftdeltatimebucket30d.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BookNFTDeltaTimeBucket30dDeleteOne is the builder for deleting a single BookNFTDeltaTimeBucket30d entity.
type BookNFTDeltaTimeBucket30dDeleteOne struct {
	_d *BookNFTDeltaTimeBucket30dDelete
}

// Where appends a list predicates to the BookNFTDeltaTimeBucket30dDelete builder.
func (_d *BookNFTDeltaTimeBucket30dDeleteOne) Where(ps ...predicate.BookNFTDeltaTimeBucket30d) *BookNFTDeltaTimeBucket30dDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BookNFTDeltaTimeBucket30dDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{booknftdeltatimebucket30d.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookNFTDeltaTimeBucket30dDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
