// Code generated by ent, DO NOT EDIT.

package ent_timescale

import (
	"fmt"
	"likecollective-indexer/ent/schema/typeutil"
	"likecollective-indexer/ent_timescale/stakingeventshypertable"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// StakingEventsHyperTable is the model entity for the StakingEventsHyperTable schema.
type StakingEventsHyperTable struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TransactionHash holds the value of the "transaction_hash" field.
	TransactionHash string `json:"transaction_hash,omitempty"`
	// TransactionIndex holds the value of the "transaction_index" field.
	TransactionIndex uint `json:"transaction_index,omitempty"`
	// BlockNumber holds the value of the "block_number" field.
	BlockNumber typeutil.Uint64 `json:"block_number,omitempty"`
	// LogIndex holds the value of the "log_index" field.
	LogIndex uint `json:"log_index,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType stakingeventshypertable.EventType `json:"event_type,omitempty"`
	// NftClassAddress holds the value of the "nft_class_address" field.
	NftClassAddress string `json:"nft_class_address,omitempty"`
	// AccountEvmAddress holds the value of the "account_evm_address" field.
	AccountEvmAddress string `json:"account_evm_address,omitempty"`
	// StakedAmountAdded holds the value of the "staked_amount_added" field.
	StakedAmountAdded typeutil.Uint256 `json:"staked_amount_added,omitempty"`
	// StakedAmountRemoved holds the value of the "staked_amount_removed" field.
	StakedAmountRemoved typeutil.Uint256 `json:"staked_amount_removed,omitempty"`
	// PendingRewardAmountAdded holds the value of the "pending_reward_amount_added" field.
	PendingRewardAmountAdded typeutil.Uint256 `json:"pending_reward_amount_added,omitempty"`
	// PendingRewardAmountRemoved holds the value of the "pending_reward_amount_removed" field.
	PendingRewardAmountRemoved typeutil.Uint256 `json:"pending_reward_amount_removed,omitempty"`
	// ClaimedRewardAmountAdded holds the value of the "claimed_reward_amount_added" field.
	ClaimedRewardAmountAdded typeutil.Uint256 `json:"claimed_reward_amount_added,omitempty"`
	// ClaimedRewardAmountRemoved holds the value of the "claimed_reward_amount_removed" field.
	ClaimedRewardAmountRemoved typeutil.Uint256 `json:"claimed_reward_amount_removed,omitempty"`
	// Datetime holds the value of the "datetime" field.
	Datetime     time.Time `json:"datetime,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StakingEventsHyperTable) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stakingeventshypertable.FieldID, stakingeventshypertable.FieldTransactionIndex, stakingeventshypertable.FieldLogIndex:
			values[i] = new(sql.NullInt64)
		case stakingeventshypertable.FieldTransactionHash, stakingeventshypertable.FieldEventType, stakingeventshypertable.FieldNftClassAddress, stakingeventshypertable.FieldAccountEvmAddress:
			values[i] = new(sql.NullString)
		case stakingeventshypertable.FieldDatetime:
			values[i] = new(sql.NullTime)
		case stakingeventshypertable.FieldBlockNumber:
			values[i] = stakingeventshypertable.ValueScanner.BlockNumber.ScanValue()
		case stakingeventshypertable.FieldStakedAmountAdded:
			values[i] = stakingeventshypertable.ValueScanner.StakedAmountAdded.ScanValue()
		case stakingeventshypertable.FieldStakedAmountRemoved:
			values[i] = stakingeventshypertable.ValueScanner.StakedAmountRemoved.ScanValue()
		case stakingeventshypertable.FieldPendingRewardAmountAdded:
			values[i] = stakingeventshypertable.ValueScanner.PendingRewardAmountAdded.ScanValue()
		case stakingeventshypertable.FieldPendingRewardAmountRemoved:
			values[i] = stakingeventshypertable.ValueScanner.PendingRewardAmountRemoved.ScanValue()
		case stakingeventshypertable.FieldClaimedRewardAmountAdded:
			values[i] = stakingeventshypertable.ValueScanner.ClaimedRewardAmountAdded.ScanValue()
		case stakingeventshypertable.FieldClaimedRewardAmountRemoved:
			values[i] = stakingeventshypertable.ValueScanner.ClaimedRewardAmountRemoved.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StakingEventsHyperTable fields.
func (_m *StakingEventsHyperTable) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stakingeventshypertable.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case stakingeventshypertable.FieldTransactionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_hash", values[i])
			} else if value.Valid {
				_m.TransactionHash = value.String
			}
		case stakingeventshypertable.FieldTransactionIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_index", values[i])
			} else if value.Valid {
				_m.TransactionIndex = uint(value.Int64)
			}
		case stakingeventshypertable.FieldBlockNumber:
			if value, err := stakingeventshypertable.ValueScanner.BlockNumber.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.BlockNumber = value
			}
		case stakingeventshypertable.FieldLogIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field log_index", values[i])
			} else if value.Valid {
				_m.LogIndex = uint(value.Int64)
			}
		case stakingeventshypertable.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = stakingeventshypertable.EventType(value.String)
			}
		case stakingeventshypertable.FieldNftClassAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nft_class_address", values[i])
			} else if value.Valid {
				_m.NftClassAddress = value.String
			}
		case stakingeventshypertable.FieldAccountEvmAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_evm_address", values[i])
			} else if value.Valid {
				_m.AccountEvmAddress = value.String
			}
		case stakingeventshypertable.FieldStakedAmountAdded:
			if value, err := stakingeventshypertable.ValueScanner.StakedAmountAdded.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.StakedAmountAdded = value
			}
		case stakingeventshypertable.FieldStakedAmountRemoved:
			if value, err := stakingeventshypertable.ValueScanner.StakedAmountRemoved.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.StakedAmountRemoved = value
			}
		case stakingeventshypertable.FieldPendingRewardAmountAdded:
			if value, err := stakingeventshypertable.ValueScanner.PendingRewardAmountAdded.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.PendingRewardAmountAdded = value
			}
		case stakingeventshypertable.FieldPendingRewardAmountRemoved:
			if value, err := stakingeventshypertable.ValueScanner.PendingRewardAmountRemoved.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.PendingRewardAmountRemoved = value
			}
		case stakingeventshypertable.FieldClaimedRewardAmountAdded:
			if value, err := stakingeventshypertable.ValueScanner.ClaimedRewardAmountAdded.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.ClaimedRewardAmountAdded = value
			}
		case stakingeventshypertable.FieldClaimedRewardAmountRemoved:
			if value, err := stakingeventshypertable.ValueScanner.ClaimedRewardAmountRemoved.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.ClaimedRewardAmountRemoved = value
			}
		case stakingeventshypertable.FieldDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field datetime", values[i])
			} else if value.Valid {
				_m.Datetime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StakingEventsHyperTable.
// This includes values selected through modifiers, order, etc.
func (_m *StakingEventsHyperTable) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StakingEventsHyperTable.
// Note that you need to call StakingEventsHyperTable.Unwrap() before calling this method if this StakingEventsHyperTable
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StakingEventsHyperTable) Update() *StakingEventsHyperTableUpdateOne {
	return NewStakingEventsHyperTableClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StakingEventsHyperTable entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StakingEventsHyperTable) Unwrap() *StakingEventsHyperTable {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent_timescale: StakingEventsHyperTable is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StakingEventsHyperTable) String() string {
	var builder strings.Builder
	builder.WriteString("StakingEventsHyperTable(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("transaction_hash=")
	builder.WriteString(_m.TransactionHash)
	builder.WriteString(", ")
	builder.WriteString("transaction_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransactionIndex))
	builder.WriteString(", ")
	builder.WriteString("block_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockNumber))
	builder.WriteString(", ")
	builder.WriteString("log_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogIndex))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventType))
	builder.WriteString(", ")
	builder.WriteString("nft_class_address=")
	builder.WriteString(_m.NftClassAddress)
	builder.WriteString(", ")
	builder.WriteString("account_evm_address=")
	builder.WriteString(_m.AccountEvmAddress)
	builder.WriteString(", ")
	builder.WriteString("staked_amount_added=")
	builder.WriteString(fmt.Sprintf("%v", _m.StakedAmountAdded))
	builder.WriteString(", ")
	builder.WriteString("staked_amount_removed=")
	builder.WriteString(fmt.Sprintf("%v", _m.StakedAmountRemoved))
	builder.WriteString(", ")
	builder.WriteString("pending_reward_amount_added=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingRewardAmountAdded))
	builder.WriteString(", ")
	builder.WriteString("pending_reward_amount_removed=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingRewardAmountRemoved))
	builder.WriteString(", ")
	builder.WriteString("claimed_reward_amount_added=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClaimedRewardAmountAdded))
	builder.WriteString(", ")
	builder.WriteString("claimed_reward_amount_removed=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClaimedRewardAmountRemoved))
	builder.WriteString(", ")
	builder.WriteString("datetime=")
	builder.WriteString(_m.Datetime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StakingEventsHyperTables is a parsable slice of StakingEventsHyperTable.
type StakingEventsHyperTables []*StakingEventsHyperTable
