// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AccountEvmAddressGet implements GET /account/{evm_address} operation.
//
// Get an account.
//
// GET /account/{evm_address}
func (UnimplementedHandler) AccountEvmAddressGet(ctx context.Context, params AccountEvmAddressGetParams) (r *Account, _ error) {
	return r, ht.ErrNotImplemented
}

// AccountEvmAddressStakingEventsEventTypeGet implements GET /account/{evm_address}/staking-events/{event_type} operation.
//
// Get staking events for an account.
//
// GET /account/{evm_address}/staking-events/{event_type}
func (UnimplementedHandler) AccountEvmAddressStakingEventsEventTypeGet(ctx context.Context, params AccountEvmAddressStakingEventsEventTypeGetParams) (r *AccountEvmAddressStakingEventsEventTypeGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// AccountEvmAddressStakingsGet implements GET /account/{evm_address}/stakings operation.
//
// Get staking information for an account.
//
// GET /account/{evm_address}/stakings
func (UnimplementedHandler) AccountEvmAddressStakingsGet(ctx context.Context, params AccountEvmAddressStakingsGetParams) (r *AccountEvmAddressStakingsGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// AccountsGet implements GET /accounts operation.
//
// Get accounts.
//
// GET /accounts
func (UnimplementedHandler) AccountsGet(ctx context.Context, params AccountsGetParams) (r *AccountsGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNftEvmAddressGet implements GET /book-nft/{evm_address} operation.
//
// Get a book NFT.
//
// GET /book-nft/{evm_address}
func (UnimplementedHandler) BookNftEvmAddressGet(ctx context.Context, params BookNftEvmAddressGetParams) (r *BookNFT, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNftEvmAddressStakingEventsEventTypeGet implements GET /book-nft/{evm_address}/staking-events/{event_type} operation.
//
// Get staking events for a book NFT.
//
// GET /book-nft/{evm_address}/staking-events/{event_type}
func (UnimplementedHandler) BookNftEvmAddressStakingEventsEventTypeGet(ctx context.Context, params BookNftEvmAddressStakingEventsEventTypeGetParams) (r *BookNftEvmAddressStakingEventsEventTypeGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNftEvmAddressStakingsGet implements GET /book-nft/{evm_address}/stakings operation.
//
// Get staking information for a book NFT.
//
// GET /book-nft/{evm_address}/stakings
func (UnimplementedHandler) BookNftEvmAddressStakingsGet(ctx context.Context, params BookNftEvmAddressStakingsGetParams) (r *BookNftEvmAddressStakingsGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNftsGet implements GET /book-nfts operation.
//
// Get book NFTs.
//
// GET /book-nfts
func (UnimplementedHandler) BookNftsGet(ctx context.Context, params BookNftsGetParams) (r *BookNftsGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// BookNftsTimeFrameDeltaGet implements GET /book-nfts/{time_frame}/delta operation.
//
// Get book NFTs.
//
// GET /book-nfts/{time_frame}/delta
func (UnimplementedHandler) BookNftsTimeFrameDeltaGet(ctx context.Context, params BookNftsTimeFrameDeltaGetParams) (r *BookNftsTimeFrameDeltaGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// EventsAddressGet implements GET /events/{address} operation.
//
// Query events.
//
// GET /events/{address}
func (UnimplementedHandler) EventsAddressGet(ctx context.Context, params EventsAddressGetParams) (r *EventsAddressGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// EventsAddressSignatureGet implements GET /events/{address}/{signature} operation.
//
// Query events.
//
// GET /events/{address}/{signature}
func (UnimplementedHandler) EventsAddressSignatureGet(ctx context.Context, params EventsAddressSignatureGetParams) (r *EventsAddressSignatureGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// EventsGet implements GET /events operation.
//
// Query events.
//
// GET /events
func (UnimplementedHandler) EventsGet(ctx context.Context, params EventsGetParams) (r *EventsGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// StakingsGet implements GET /stakings operation.
//
// Get stakings.
//
// GET /stakings
func (UnimplementedHandler) StakingsGet(ctx context.Context, params StakingsGetParams) (r *StakingsGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
