// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"likenft-indexer/ent/evmevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EVMEventCreate is the builder for creating a EVMEvent entity.
type EVMEventCreate struct {
	config
	mutation *EVMEventMutation
	hooks    []Hook
}

// SetTransactionHash sets the "transaction_hash" field.
func (eec *EVMEventCreate) SetTransactionHash(s string) *EVMEventCreate {
	eec.mutation.SetTransactionHash(s)
	return eec
}

// SetBlockHash sets the "block_hash" field.
func (eec *EVMEventCreate) SetBlockHash(s string) *EVMEventCreate {
	eec.mutation.SetBlockHash(s)
	return eec
}

// SetBlockNumber sets the "block_number" field.
func (eec *EVMEventCreate) SetBlockNumber(u uint64) *EVMEventCreate {
	eec.mutation.SetBlockNumber(u)
	return eec
}

// SetLogIndex sets the "log_index" field.
func (eec *EVMEventCreate) SetLogIndex(u uint64) *EVMEventCreate {
	eec.mutation.SetLogIndex(u)
	return eec
}

// SetAddress sets the "address" field.
func (eec *EVMEventCreate) SetAddress(s string) *EVMEventCreate {
	eec.mutation.SetAddress(s)
	return eec
}

// SetTopic0 sets the "topic0" field.
func (eec *EVMEventCreate) SetTopic0(s string) *EVMEventCreate {
	eec.mutation.SetTopic0(s)
	return eec
}

// SetTopic1 sets the "topic1" field.
func (eec *EVMEventCreate) SetTopic1(s string) *EVMEventCreate {
	eec.mutation.SetTopic1(s)
	return eec
}

// SetTopic2 sets the "topic2" field.
func (eec *EVMEventCreate) SetTopic2(s string) *EVMEventCreate {
	eec.mutation.SetTopic2(s)
	return eec
}

// SetTopic3 sets the "topic3" field.
func (eec *EVMEventCreate) SetTopic3(s string) *EVMEventCreate {
	eec.mutation.SetTopic3(s)
	return eec
}

// SetData sets the "data" field.
func (eec *EVMEventCreate) SetData(s string) *EVMEventCreate {
	eec.mutation.SetData(s)
	return eec
}

// SetTimestamp sets the "timestamp" field.
func (eec *EVMEventCreate) SetTimestamp(t time.Time) *EVMEventCreate {
	eec.mutation.SetTimestamp(t)
	return eec
}

// Mutation returns the EVMEventMutation object of the builder.
func (eec *EVMEventCreate) Mutation() *EVMEventMutation {
	return eec.mutation
}

// Save creates the EVMEvent in the database.
func (eec *EVMEventCreate) Save(ctx context.Context) (*EVMEvent, error) {
	return withHooks(ctx, eec.sqlSave, eec.mutation, eec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (eec *EVMEventCreate) SaveX(ctx context.Context) *EVMEvent {
	v, err := eec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eec *EVMEventCreate) Exec(ctx context.Context) error {
	_, err := eec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eec *EVMEventCreate) ExecX(ctx context.Context) {
	if err := eec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eec *EVMEventCreate) check() error {
	if _, ok := eec.mutation.TransactionHash(); !ok {
		return &ValidationError{Name: "transaction_hash", err: errors.New(`ent: missing required field "EVMEvent.transaction_hash"`)}
	}
	if v, ok := eec.mutation.TransactionHash(); ok {
		if err := evmevent.TransactionHashValidator(v); err != nil {
			return &ValidationError{Name: "transaction_hash", err: fmt.Errorf(`ent: validator failed for field "EVMEvent.transaction_hash": %w`, err)}
		}
	}
	if _, ok := eec.mutation.BlockHash(); !ok {
		return &ValidationError{Name: "block_hash", err: errors.New(`ent: missing required field "EVMEvent.block_hash"`)}
	}
	if v, ok := eec.mutation.BlockHash(); ok {
		if err := evmevent.BlockHashValidator(v); err != nil {
			return &ValidationError{Name: "block_hash", err: fmt.Errorf(`ent: validator failed for field "EVMEvent.block_hash": %w`, err)}
		}
	}
	if _, ok := eec.mutation.BlockNumber(); !ok {
		return &ValidationError{Name: "block_number", err: errors.New(`ent: missing required field "EVMEvent.block_number"`)}
	}
	if _, ok := eec.mutation.LogIndex(); !ok {
		return &ValidationError{Name: "log_index", err: errors.New(`ent: missing required field "EVMEvent.log_index"`)}
	}
	if _, ok := eec.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "EVMEvent.address"`)}
	}
	if v, ok := eec.mutation.Address(); ok {
		if err := evmevent.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "EVMEvent.address": %w`, err)}
		}
	}
	if _, ok := eec.mutation.Topic0(); !ok {
		return &ValidationError{Name: "topic0", err: errors.New(`ent: missing required field "EVMEvent.topic0"`)}
	}
	if v, ok := eec.mutation.Topic0(); ok {
		if err := evmevent.Topic0Validator(v); err != nil {
			return &ValidationError{Name: "topic0", err: fmt.Errorf(`ent: validator failed for field "EVMEvent.topic0": %w`, err)}
		}
	}
	if _, ok := eec.mutation.Topic1(); !ok {
		return &ValidationError{Name: "topic1", err: errors.New(`ent: missing required field "EVMEvent.topic1"`)}
	}
	if _, ok := eec.mutation.Topic2(); !ok {
		return &ValidationError{Name: "topic2", err: errors.New(`ent: missing required field "EVMEvent.topic2"`)}
	}
	if _, ok := eec.mutation.Topic3(); !ok {
		return &ValidationError{Name: "topic3", err: errors.New(`ent: missing required field "EVMEvent.topic3"`)}
	}
	if _, ok := eec.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "EVMEvent.data"`)}
	}
	if _, ok := eec.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "EVMEvent.timestamp"`)}
	}
	return nil
}

func (eec *EVMEventCreate) sqlSave(ctx context.Context) (*EVMEvent, error) {
	if err := eec.check(); err != nil {
		return nil, err
	}
	_node, _spec := eec.createSpec()
	if err := sqlgraph.CreateNode(ctx, eec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	eec.mutation.id = &_node.ID
	eec.mutation.done = true
	return _node, nil
}

func (eec *EVMEventCreate) createSpec() (*EVMEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &EVMEvent{config: eec.config}
		_spec = sqlgraph.NewCreateSpec(evmevent.Table, sqlgraph.NewFieldSpec(evmevent.FieldID, field.TypeInt))
	)
	if value, ok := eec.mutation.TransactionHash(); ok {
		_spec.SetField(evmevent.FieldTransactionHash, field.TypeString, value)
		_node.TransactionHash = value
	}
	if value, ok := eec.mutation.BlockHash(); ok {
		_spec.SetField(evmevent.FieldBlockHash, field.TypeString, value)
		_node.BlockHash = value
	}
	if value, ok := eec.mutation.BlockNumber(); ok {
		_spec.SetField(evmevent.FieldBlockNumber, field.TypeUint64, value)
		_node.BlockNumber = value
	}
	if value, ok := eec.mutation.LogIndex(); ok {
		_spec.SetField(evmevent.FieldLogIndex, field.TypeUint64, value)
		_node.LogIndex = value
	}
	if value, ok := eec.mutation.Address(); ok {
		_spec.SetField(evmevent.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := eec.mutation.Topic0(); ok {
		_spec.SetField(evmevent.FieldTopic0, field.TypeString, value)
		_node.Topic0 = value
	}
	if value, ok := eec.mutation.Topic1(); ok {
		_spec.SetField(evmevent.FieldTopic1, field.TypeString, value)
		_node.Topic1 = value
	}
	if value, ok := eec.mutation.Topic2(); ok {
		_spec.SetField(evmevent.FieldTopic2, field.TypeString, value)
		_node.Topic2 = value
	}
	if value, ok := eec.mutation.Topic3(); ok {
		_spec.SetField(evmevent.FieldTopic3, field.TypeString, value)
		_node.Topic3 = value
	}
	if value, ok := eec.mutation.Data(); ok {
		_spec.SetField(evmevent.FieldData, field.TypeString, value)
		_node.Data = value
	}
	if value, ok := eec.mutation.Timestamp(); ok {
		_spec.SetField(evmevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	return _node, _spec
}

// EVMEventCreateBulk is the builder for creating many EVMEvent entities in bulk.
type EVMEventCreateBulk struct {
	config
	err      error
	builders []*EVMEventCreate
}

// Save creates the EVMEvent entities in the database.
func (eecb *EVMEventCreateBulk) Save(ctx context.Context) ([]*EVMEvent, error) {
	if eecb.err != nil {
		return nil, eecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(eecb.builders))
	nodes := make([]*EVMEvent, len(eecb.builders))
	mutators := make([]Mutator, len(eecb.builders))
	for i := range eecb.builders {
		func(i int, root context.Context) {
			builder := eecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EVMEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eecb *EVMEventCreateBulk) SaveX(ctx context.Context) []*EVMEvent {
	v, err := eecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eecb *EVMEventCreateBulk) Exec(ctx context.Context) error {
	_, err := eecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eecb *EVMEventCreateBulk) ExecX(ctx context.Context) {
	if err := eecb.Exec(ctx); err != nil {
		panic(err)
	}
}
