// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"likenft-indexer/ent/evmevent"
	"likenft-indexer/ent/schema/typeutil"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EVMEvent is the model entity for the EVMEvent schema.
type EVMEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TransactionHash holds the value of the "transaction_hash" field.
	TransactionHash string `json:"transaction_hash,omitempty"`
	// TransactionIndex holds the value of the "transaction_index" field.
	TransactionIndex uint `json:"transaction_index,omitempty"`
	// ChainID holds the value of the "chain_id" field.
	ChainID typeutil.Uint64 `json:"chain_id,omitempty"`
	// BlockHash holds the value of the "block_hash" field.
	BlockHash string `json:"block_hash,omitempty"`
	// BlockNumber holds the value of the "block_number" field.
	BlockNumber typeutil.Uint64 `json:"block_number,omitempty"`
	// LogIndex holds the value of the "log_index" field.
	LogIndex uint `json:"log_index,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Topic0 holds the value of the "topic0" field.
	Topic0 string `json:"topic0,omitempty"`
	// Topic0Hex holds the value of the "topic0_hex" field.
	Topic0Hex string `json:"topic0_hex,omitempty"`
	// Topic1 holds the value of the "topic1" field.
	Topic1 *string `json:"topic1,omitempty"`
	// Topic1Hex holds the value of the "topic1_hex" field.
	Topic1Hex *string `json:"topic1_hex,omitempty"`
	// Topic2 holds the value of the "topic2" field.
	Topic2 *string `json:"topic2,omitempty"`
	// Topic2Hex holds the value of the "topic2_hex" field.
	Topic2Hex *string `json:"topic2_hex,omitempty"`
	// Topic3 holds the value of the "topic3" field.
	Topic3 *string `json:"topic3,omitempty"`
	// Topic3Hex holds the value of the "topic3_hex" field.
	Topic3Hex *string `json:"topic3_hex,omitempty"`
	// Data holds the value of the "data" field.
	Data *string `json:"data,omitempty"`
	// DataHex holds the value of the "data_hex" field.
	DataHex *string `json:"data_hex,omitempty"`
	// Removed holds the value of the "removed" field.
	Removed bool `json:"removed,omitempty"`
	// Status holds the value of the "status" field.
	Status evmevent.Status `json:"status,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Signature holds the value of the "signature" field.
	Signature string `json:"signature,omitempty"`
	// IndexedParams holds the value of the "indexed_params" field.
	IndexedParams map[string]interface{} `json:"indexed_params,omitempty"`
	// NonIndexedParams holds the value of the "non_indexed_params" field.
	NonIndexedParams map[string]interface{} `json:"non_indexed_params,omitempty"`
	// FailedReason holds the value of the "failed_reason" field.
	FailedReason *string `json:"failed_reason,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp    time.Time `json:"timestamp,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EVMEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case evmevent.FieldIndexedParams, evmevent.FieldNonIndexedParams:
			values[i] = new([]byte)
		case evmevent.FieldRemoved:
			values[i] = new(sql.NullBool)
		case evmevent.FieldID, evmevent.FieldTransactionIndex, evmevent.FieldLogIndex:
			values[i] = new(sql.NullInt64)
		case evmevent.FieldTransactionHash, evmevent.FieldBlockHash, evmevent.FieldAddress, evmevent.FieldTopic0, evmevent.FieldTopic0Hex, evmevent.FieldTopic1, evmevent.FieldTopic1Hex, evmevent.FieldTopic2, evmevent.FieldTopic2Hex, evmevent.FieldTopic3, evmevent.FieldTopic3Hex, evmevent.FieldData, evmevent.FieldDataHex, evmevent.FieldStatus, evmevent.FieldName, evmevent.FieldSignature, evmevent.FieldFailedReason:
			values[i] = new(sql.NullString)
		case evmevent.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case evmevent.FieldChainID:
			values[i] = evmevent.ValueScanner.ChainID.ScanValue()
		case evmevent.FieldBlockNumber:
			values[i] = evmevent.ValueScanner.BlockNumber.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EVMEvent fields.
func (ee *EVMEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case evmevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ee.ID = int(value.Int64)
		case evmevent.FieldTransactionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_hash", values[i])
			} else if value.Valid {
				ee.TransactionHash = value.String
			}
		case evmevent.FieldTransactionIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_index", values[i])
			} else if value.Valid {
				ee.TransactionIndex = uint(value.Int64)
			}
		case evmevent.FieldChainID:
			if value, err := evmevent.ValueScanner.ChainID.FromValue(values[i]); err != nil {
				return err
			} else {
				ee.ChainID = value
			}
		case evmevent.FieldBlockHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field block_hash", values[i])
			} else if value.Valid {
				ee.BlockHash = value.String
			}
		case evmevent.FieldBlockNumber:
			if value, err := evmevent.ValueScanner.BlockNumber.FromValue(values[i]); err != nil {
				return err
			} else {
				ee.BlockNumber = value
			}
		case evmevent.FieldLogIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field log_index", values[i])
			} else if value.Valid {
				ee.LogIndex = uint(value.Int64)
			}
		case evmevent.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				ee.Address = value.String
			}
		case evmevent.FieldTopic0:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic0", values[i])
			} else if value.Valid {
				ee.Topic0 = value.String
			}
		case evmevent.FieldTopic0Hex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic0_hex", values[i])
			} else if value.Valid {
				ee.Topic0Hex = value.String
			}
		case evmevent.FieldTopic1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic1", values[i])
			} else if value.Valid {
				ee.Topic1 = new(string)
				*ee.Topic1 = value.String
			}
		case evmevent.FieldTopic1Hex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic1_hex", values[i])
			} else if value.Valid {
				ee.Topic1Hex = new(string)
				*ee.Topic1Hex = value.String
			}
		case evmevent.FieldTopic2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic2", values[i])
			} else if value.Valid {
				ee.Topic2 = new(string)
				*ee.Topic2 = value.String
			}
		case evmevent.FieldTopic2Hex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic2_hex", values[i])
			} else if value.Valid {
				ee.Topic2Hex = new(string)
				*ee.Topic2Hex = value.String
			}
		case evmevent.FieldTopic3:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic3", values[i])
			} else if value.Valid {
				ee.Topic3 = new(string)
				*ee.Topic3 = value.String
			}
		case evmevent.FieldTopic3Hex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic3_hex", values[i])
			} else if value.Valid {
				ee.Topic3Hex = new(string)
				*ee.Topic3Hex = value.String
			}
		case evmevent.FieldData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value.Valid {
				ee.Data = new(string)
				*ee.Data = value.String
			}
		case evmevent.FieldDataHex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_hex", values[i])
			} else if value.Valid {
				ee.DataHex = new(string)
				*ee.DataHex = value.String
			}
		case evmevent.FieldRemoved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field removed", values[i])
			} else if value.Valid {
				ee.Removed = value.Bool
			}
		case evmevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ee.Status = evmevent.Status(value.String)
			}
		case evmevent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ee.Name = value.String
			}
		case evmevent.FieldSignature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signature", values[i])
			} else if value.Valid {
				ee.Signature = value.String
			}
		case evmevent.FieldIndexedParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field indexed_params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ee.IndexedParams); err != nil {
					return fmt.Errorf("unmarshal field indexed_params: %w", err)
				}
			}
		case evmevent.FieldNonIndexedParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field non_indexed_params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ee.NonIndexedParams); err != nil {
					return fmt.Errorf("unmarshal field non_indexed_params: %w", err)
				}
			}
		case evmevent.FieldFailedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failed_reason", values[i])
			} else if value.Valid {
				ee.FailedReason = new(string)
				*ee.FailedReason = value.String
			}
		case evmevent.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				ee.Timestamp = value.Time
			}
		default:
			ee.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EVMEvent.
// This includes values selected through modifiers, order, etc.
func (ee *EVMEvent) Value(name string) (ent.Value, error) {
	return ee.selectValues.Get(name)
}

// Update returns a builder for updating this EVMEvent.
// Note that you need to call EVMEvent.Unwrap() before calling this method if this EVMEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ee *EVMEvent) Update() *EVMEventUpdateOne {
	return NewEVMEventClient(ee.config).UpdateOne(ee)
}

// Unwrap unwraps the EVMEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ee *EVMEvent) Unwrap() *EVMEvent {
	_tx, ok := ee.config.driver.(*txDriver)
	if !ok {
		panic("ent: EVMEvent is not a transactional entity")
	}
	ee.config.driver = _tx.drv
	return ee
}

// String implements the fmt.Stringer.
func (ee *EVMEvent) String() string {
	var builder strings.Builder
	builder.WriteString("EVMEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ee.ID))
	builder.WriteString("transaction_hash=")
	builder.WriteString(ee.TransactionHash)
	builder.WriteString(", ")
	builder.WriteString("transaction_index=")
	builder.WriteString(fmt.Sprintf("%v", ee.TransactionIndex))
	builder.WriteString(", ")
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", ee.ChainID))
	builder.WriteString(", ")
	builder.WriteString("block_hash=")
	builder.WriteString(ee.BlockHash)
	builder.WriteString(", ")
	builder.WriteString("block_number=")
	builder.WriteString(fmt.Sprintf("%v", ee.BlockNumber))
	builder.WriteString(", ")
	builder.WriteString("log_index=")
	builder.WriteString(fmt.Sprintf("%v", ee.LogIndex))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(ee.Address)
	builder.WriteString(", ")
	builder.WriteString("topic0=")
	builder.WriteString(ee.Topic0)
	builder.WriteString(", ")
	builder.WriteString("topic0_hex=")
	builder.WriteString(ee.Topic0Hex)
	builder.WriteString(", ")
	if v := ee.Topic1; v != nil {
		builder.WriteString("topic1=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ee.Topic1Hex; v != nil {
		builder.WriteString("topic1_hex=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ee.Topic2; v != nil {
		builder.WriteString("topic2=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ee.Topic2Hex; v != nil {
		builder.WriteString("topic2_hex=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ee.Topic3; v != nil {
		builder.WriteString("topic3=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ee.Topic3Hex; v != nil {
		builder.WriteString("topic3_hex=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ee.Data; v != nil {
		builder.WriteString("data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ee.DataHex; v != nil {
		builder.WriteString("data_hex=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("removed=")
	builder.WriteString(fmt.Sprintf("%v", ee.Removed))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ee.Status))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ee.Name)
	builder.WriteString(", ")
	builder.WriteString("signature=")
	builder.WriteString(ee.Signature)
	builder.WriteString(", ")
	builder.WriteString("indexed_params=")
	builder.WriteString(fmt.Sprintf("%v", ee.IndexedParams))
	builder.WriteString(", ")
	builder.WriteString("non_indexed_params=")
	builder.WriteString(fmt.Sprintf("%v", ee.NonIndexedParams))
	builder.WriteString(", ")
	if v := ee.FailedReason; v != nil {
		builder.WriteString("failed_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(ee.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EVMEvents is a parsable slice of EVMEvent.
type EVMEvents []*EVMEvent
