// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"likenft-indexer/ent/account"
	"likenft-indexer/ent/nft"
	"likenft-indexer/ent/nftclass"
	"likenft-indexer/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NFTClassQuery is the builder for querying NFTClass entities.
type NFTClassQuery struct {
	config
	ctx        *QueryContext
	order      []nftclass.OrderOption
	inters     []Interceptor
	predicates []predicate.NFTClass
	withNfts   *NFTQuery
	withOwner  *AccountQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NFTClassQuery builder.
func (ncq *NFTClassQuery) Where(ps ...predicate.NFTClass) *NFTClassQuery {
	ncq.predicates = append(ncq.predicates, ps...)
	return ncq
}

// Limit the number of records to be returned by this query.
func (ncq *NFTClassQuery) Limit(limit int) *NFTClassQuery {
	ncq.ctx.Limit = &limit
	return ncq
}

// Offset to start from.
func (ncq *NFTClassQuery) Offset(offset int) *NFTClassQuery {
	ncq.ctx.Offset = &offset
	return ncq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ncq *NFTClassQuery) Unique(unique bool) *NFTClassQuery {
	ncq.ctx.Unique = &unique
	return ncq
}

// Order specifies how the records should be ordered.
func (ncq *NFTClassQuery) Order(o ...nftclass.OrderOption) *NFTClassQuery {
	ncq.order = append(ncq.order, o...)
	return ncq
}

// QueryNfts chains the current query on the "nfts" edge.
func (ncq *NFTClassQuery) QueryNfts() *NFTQuery {
	query := (&NFTClient{config: ncq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ncq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ncq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nftclass.Table, nftclass.FieldID, selector),
			sqlgraph.To(nft.Table, nft.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, nftclass.NftsTable, nftclass.NftsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ncq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwner chains the current query on the "owner" edge.
func (ncq *NFTClassQuery) QueryOwner() *AccountQuery {
	query := (&AccountClient{config: ncq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ncq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ncq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nftclass.Table, nftclass.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nftclass.OwnerTable, nftclass.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(ncq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NFTClass entity from the query.
// Returns a *NotFoundError when no NFTClass was found.
func (ncq *NFTClassQuery) First(ctx context.Context) (*NFTClass, error) {
	nodes, err := ncq.Limit(1).All(setContextOp(ctx, ncq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nftclass.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ncq *NFTClassQuery) FirstX(ctx context.Context) *NFTClass {
	node, err := ncq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NFTClass ID from the query.
// Returns a *NotFoundError when no NFTClass ID was found.
func (ncq *NFTClassQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ncq.Limit(1).IDs(setContextOp(ctx, ncq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nftclass.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ncq *NFTClassQuery) FirstIDX(ctx context.Context) int {
	id, err := ncq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NFTClass entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NFTClass entity is found.
// Returns a *NotFoundError when no NFTClass entities are found.
func (ncq *NFTClassQuery) Only(ctx context.Context) (*NFTClass, error) {
	nodes, err := ncq.Limit(2).All(setContextOp(ctx, ncq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nftclass.Label}
	default:
		return nil, &NotSingularError{nftclass.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ncq *NFTClassQuery) OnlyX(ctx context.Context) *NFTClass {
	node, err := ncq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NFTClass ID in the query.
// Returns a *NotSingularError when more than one NFTClass ID is found.
// Returns a *NotFoundError when no entities are found.
func (ncq *NFTClassQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ncq.Limit(2).IDs(setContextOp(ctx, ncq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nftclass.Label}
	default:
		err = &NotSingularError{nftclass.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ncq *NFTClassQuery) OnlyIDX(ctx context.Context) int {
	id, err := ncq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NFTClasses.
func (ncq *NFTClassQuery) All(ctx context.Context) ([]*NFTClass, error) {
	ctx = setContextOp(ctx, ncq.ctx, ent.OpQueryAll)
	if err := ncq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NFTClass, *NFTClassQuery]()
	return withInterceptors[[]*NFTClass](ctx, ncq, qr, ncq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ncq *NFTClassQuery) AllX(ctx context.Context) []*NFTClass {
	nodes, err := ncq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NFTClass IDs.
func (ncq *NFTClassQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ncq.ctx.Unique == nil && ncq.path != nil {
		ncq.Unique(true)
	}
	ctx = setContextOp(ctx, ncq.ctx, ent.OpQueryIDs)
	if err = ncq.Select(nftclass.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ncq *NFTClassQuery) IDsX(ctx context.Context) []int {
	ids, err := ncq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ncq *NFTClassQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ncq.ctx, ent.OpQueryCount)
	if err := ncq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ncq, querierCount[*NFTClassQuery](), ncq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ncq *NFTClassQuery) CountX(ctx context.Context) int {
	count, err := ncq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ncq *NFTClassQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ncq.ctx, ent.OpQueryExist)
	switch _, err := ncq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ncq *NFTClassQuery) ExistX(ctx context.Context) bool {
	exist, err := ncq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NFTClassQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ncq *NFTClassQuery) Clone() *NFTClassQuery {
	if ncq == nil {
		return nil
	}
	return &NFTClassQuery{
		config:     ncq.config,
		ctx:        ncq.ctx.Clone(),
		order:      append([]nftclass.OrderOption{}, ncq.order...),
		inters:     append([]Interceptor{}, ncq.inters...),
		predicates: append([]predicate.NFTClass{}, ncq.predicates...),
		withNfts:   ncq.withNfts.Clone(),
		withOwner:  ncq.withOwner.Clone(),
		// clone intermediate query.
		sql:  ncq.sql.Clone(),
		path: ncq.path,
	}
}

// WithNfts tells the query-builder to eager-load the nodes that are connected to
// the "nfts" edge. The optional arguments are used to configure the query builder of the edge.
func (ncq *NFTClassQuery) WithNfts(opts ...func(*NFTQuery)) *NFTClassQuery {
	query := (&NFTClient{config: ncq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ncq.withNfts = query
	return ncq
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (ncq *NFTClassQuery) WithOwner(opts ...func(*AccountQuery)) *NFTClassQuery {
	query := (&AccountClient{config: ncq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ncq.withOwner = query
	return ncq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AcquireBookNftEventsWeight float64 `json:"acquire_book_nft_events_weight,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NFTClass.Query().
//		GroupBy(nftclass.FieldAcquireBookNftEventsWeight).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ncq *NFTClassQuery) GroupBy(field string, fields ...string) *NFTClassGroupBy {
	ncq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NFTClassGroupBy{build: ncq}
	grbuild.flds = &ncq.ctx.Fields
	grbuild.label = nftclass.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AcquireBookNftEventsWeight float64 `json:"acquire_book_nft_events_weight,omitempty"`
//	}
//
//	client.NFTClass.Query().
//		Select(nftclass.FieldAcquireBookNftEventsWeight).
//		Scan(ctx, &v)
func (ncq *NFTClassQuery) Select(fields ...string) *NFTClassSelect {
	ncq.ctx.Fields = append(ncq.ctx.Fields, fields...)
	sbuild := &NFTClassSelect{NFTClassQuery: ncq}
	sbuild.label = nftclass.Label
	sbuild.flds, sbuild.scan = &ncq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NFTClassSelect configured with the given aggregations.
func (ncq *NFTClassQuery) Aggregate(fns ...AggregateFunc) *NFTClassSelect {
	return ncq.Select().Aggregate(fns...)
}

func (ncq *NFTClassQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ncq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ncq); err != nil {
				return err
			}
		}
	}
	for _, f := range ncq.ctx.Fields {
		if !nftclass.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ncq.path != nil {
		prev, err := ncq.path(ctx)
		if err != nil {
			return err
		}
		ncq.sql = prev
	}
	return nil
}

func (ncq *NFTClassQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NFTClass, error) {
	var (
		nodes       = []*NFTClass{}
		withFKs     = ncq.withFKs
		_spec       = ncq.querySpec()
		loadedTypes = [2]bool{
			ncq.withNfts != nil,
			ncq.withOwner != nil,
		}
	)
	if ncq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, nftclass.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NFTClass).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NFTClass{config: ncq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ncq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ncq.withNfts; query != nil {
		if err := ncq.loadNfts(ctx, query, nodes,
			func(n *NFTClass) { n.Edges.Nfts = []*NFT{} },
			func(n *NFTClass, e *NFT) { n.Edges.Nfts = append(n.Edges.Nfts, e) }); err != nil {
			return nil, err
		}
	}
	if query := ncq.withOwner; query != nil {
		if err := ncq.loadOwner(ctx, query, nodes, nil,
			func(n *NFTClass, e *Account) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ncq *NFTClassQuery) loadNfts(ctx context.Context, query *NFTQuery, nodes []*NFTClass, init func(*NFTClass), assign func(*NFTClass, *NFT)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*NFTClass)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.NFT(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(nftclass.NftsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.nft_class_nfts
		if fk == nil {
			return fmt.Errorf(`foreign-key "nft_class_nfts" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "nft_class_nfts" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (ncq *NFTClassQuery) loadOwner(ctx context.Context, query *AccountQuery, nodes []*NFTClass, init func(*NFTClass), assign func(*NFTClass, *Account)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*NFTClass)
	for i := range nodes {
		if nodes[i].account_nft_classes == nil {
			continue
		}
		fk := *nodes[i].account_nft_classes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(account.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "account_nft_classes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ncq *NFTClassQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ncq.querySpec()
	_spec.Node.Columns = ncq.ctx.Fields
	if len(ncq.ctx.Fields) > 0 {
		_spec.Unique = ncq.ctx.Unique != nil && *ncq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ncq.driver, _spec)
}

func (ncq *NFTClassQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nftclass.Table, nftclass.Columns, sqlgraph.NewFieldSpec(nftclass.FieldID, field.TypeInt))
	_spec.From = ncq.sql
	if unique := ncq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ncq.path != nil {
		_spec.Unique = true
	}
	if fields := ncq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nftclass.FieldID)
		for i := range fields {
			if fields[i] != nftclass.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ncq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ncq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ncq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ncq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ncq *NFTClassQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ncq.driver.Dialect())
	t1 := builder.Table(nftclass.Table)
	columns := ncq.ctx.Fields
	if len(columns) == 0 {
		columns = nftclass.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ncq.sql != nil {
		selector = ncq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ncq.ctx.Unique != nil && *ncq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ncq.predicates {
		p(selector)
	}
	for _, p := range ncq.order {
		p(selector)
	}
	if offset := ncq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ncq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NFTClassGroupBy is the group-by builder for NFTClass entities.
type NFTClassGroupBy struct {
	selector
	build *NFTClassQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ncgb *NFTClassGroupBy) Aggregate(fns ...AggregateFunc) *NFTClassGroupBy {
	ncgb.fns = append(ncgb.fns, fns...)
	return ncgb
}

// Scan applies the selector query and scans the result into the given value.
func (ncgb *NFTClassGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ncgb.build.ctx, ent.OpQueryGroupBy)
	if err := ncgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NFTClassQuery, *NFTClassGroupBy](ctx, ncgb.build, ncgb, ncgb.build.inters, v)
}

func (ncgb *NFTClassGroupBy) sqlScan(ctx context.Context, root *NFTClassQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ncgb.fns))
	for _, fn := range ncgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ncgb.flds)+len(ncgb.fns))
		for _, f := range *ncgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ncgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ncgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NFTClassSelect is the builder for selecting fields of NFTClass entities.
type NFTClassSelect struct {
	*NFTClassQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ncs *NFTClassSelect) Aggregate(fns ...AggregateFunc) *NFTClassSelect {
	ncs.fns = append(ncs.fns, fns...)
	return ncs
}

// Scan applies the selector query and scans the result into the given value.
func (ncs *NFTClassSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ncs.ctx, ent.OpQuerySelect)
	if err := ncs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NFTClassQuery, *NFTClassSelect](ctx, ncs.NFTClassQuery, ncs, ncs.inters, v)
}

func (ncs *NFTClassSelect) sqlScan(ctx context.Context, root *NFTClassQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ncs.fns))
	for _, fn := range ncs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ncs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ncs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
