// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"likenft-indexer/ent/nftclass"
	"likenft-indexer/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NFTClassDelete is the builder for deleting a NFTClass entity.
type NFTClassDelete struct {
	config
	hooks    []Hook
	mutation *NFTClassMutation
}

// Where appends a list predicates to the NFTClassDelete builder.
func (ncd *NFTClassDelete) Where(ps ...predicate.NFTClass) *NFTClassDelete {
	ncd.mutation.Where(ps...)
	return ncd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ncd *NFTClassDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ncd.sqlExec, ncd.mutation, ncd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ncd *NFTClassDelete) ExecX(ctx context.Context) int {
	n, err := ncd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ncd *NFTClassDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nftclass.Table, sqlgraph.NewFieldSpec(nftclass.FieldID, field.TypeInt))
	if ps := ncd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ncd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ncd.mutation.done = true
	return affected, err
}

// NFTClassDeleteOne is the builder for deleting a single NFTClass entity.
type NFTClassDeleteOne struct {
	ncd *NFTClassDelete
}

// Where appends a list predicates to the NFTClassDelete builder.
func (ncdo *NFTClassDeleteOne) Where(ps ...predicate.NFTClass) *NFTClassDeleteOne {
	ncdo.ncd.mutation.Where(ps...)
	return ncdo
}

// Exec executes the deletion query.
func (ncdo *NFTClassDeleteOne) Exec(ctx context.Context) error {
	n, err := ncdo.ncd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nftclass.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ncdo *NFTClassDeleteOne) ExecX(ctx context.Context) {
	if err := ncdo.Exec(ctx); err != nil {
		panic(err)
	}
}
