#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "$DB_NAME-owner" NOLOGIN;

    CREATE USER "$DB_USER" WITH ENCRYPTED PASSWORD '$DB_PASSWORD';

    GRANT "$DB_NAME-owner" TO "$DB_NAME";

    CREATE DATABASE "$DB_NAME" WITH ENCODING=UTF8 OWNER="$DB_NAME-owner";
    REVOKE CONNECT ON DATABASE "$DB_NAME" FROM public;
    ALTER ROLE "$DB_NAME-owner" CONNECTION LIMIT 10;
EOSQL
